repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [ --remove-all-unused-imports, --in-place ]

  -   repo: local
      hooks:
        -   id: mypy
            name: mypy
            entry: bash -c 'poetry run mypy --strict joptional'
            language: system
            types: [ python ]
            pass_filenames: false

  -   repo: local
      hooks:
        -   id: pytest
            name: pytest
            entry: bash -c 'poetry run pytest'
            language: system
            types: [ python ]
            pass_filenames: false
